import type { PlatformInfo } from '@shared/api.interface';

export const PLATFORMS: PlatformInfo[] = [
  // ========== 国内 18 家 ==========
  {
    key: 'zhipu',
    name: '智谱AI',
    region: 'domestic',
    websiteUrl: 'https://www.zhipuai.cn',
    consoleUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    apiDocUrl: 'https://open.bigmodel.cn/dev/api',
    freeTierInfo: [
      '新用户注册赠送一定额度的免费 token',
      'GLM-4-Flash 等轻量模型提供免费调用额度',
      '每日有免费调用次数限制',
    ],
    rateLimitInfo: [
      '免费版有 TPM/RPM 限制',
      '不同模型速率限制不同，需查看文档',
      '超出限制返回 429 错误',
    ],
    usageMethodInfo: [
      '兼容 OpenAI Chat Completions API',
      '支持流式和非流式调用',
      '支持函数调用、多模态等高级功能',
    ],
    validityInfo: [
      '免费额度有有效期，过期清零',
      '付费额度长期有效',
      '账户余额可在控制台查看',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'glm-4-flash',
    apiBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'bearer',
    hasUsageApi: true,
    usageApiNote: '提供用量查询接口，可查看额度消耗情况',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://open.bigmodel.cn/api/paas/v4/models',
  },
  {
    key: 'qianfan',
    name: '百度千帆/文心一言',
    region: 'domestic',
    websiteUrl: 'https://cloud.baidu.com/product/wenxinworkshop',
    consoleUrl: 'https://console.bce.baidu.com/qianfan',
    apiDocUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP',
    freeTierInfo: [
      '部分模型提供免费调用额度',
      '新用户可领取免费资源包',
      'ERNIE-Speed 等轻量模型免费',
    ],
    rateLimitInfo: [
      '不同模型有不同的 QPS 限制',
      '免费版 QPS 较低，付费可提升',
      '超出限制返回错误码',
    ],
    usageMethodInfo: [
      '兼容 OpenAI Chat Completions API',
      '支持文生图、Embedding 等多种能力',
      '支持知识库和插件功能',
    ],
    validityInfo: [
      '免费资源包有使用期限',
      '按量付费无有效期限制',
      '可在控制台查看用量明细',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'ernie_speed',
    apiBaseUrl: 'https://qianfan.baidubce.com/v2',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在控制台查看用量，无公开 API',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://qianfan.baidubce.com/v2/models',
  },
  {
    key: 'bailian',
    name: '阿里百炼/通义千问',
    region: 'domestic',
    websiteUrl: 'https://bailian.aliyun.com',
    consoleUrl: 'https://bailian.console.aliyun.com',
    apiDocUrl: 'https://help.aliyun.com/zh/model-studio',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Qwen-Turbo 等模型提供免费调用',
      '有百万 token 免费体验包',
    ],
    rateLimitInfo: [
      '不同模型有不同的 RPM/TPM 限制',
      '免费版有速率限制',
      '可通过付费提升限额',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持多模态、函数调用等',
      '支持应用搭建和知识库',
    ],
    validityInfo: [
      '免费额度有有效期',
      '按量付费按实际使用结算',
      '可在控制台查看账单',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'qwen-turbo',
    apiBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在阿里云控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1/models',
  },
  {
    key: 'hunyuan',
    name: '腾讯混元',
    region: 'domestic',
    websiteUrl: 'https://hunyuan.tencent.com',
    consoleUrl: 'https://console.cloud.tencent.com/hunyuan',
    apiDocUrl: 'https://cloud.tencent.com/document/product/1729',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Hunyuan-Lite 模型免费调用',
      '有一定量的免费 token',
    ],
    rateLimitInfo: [
      '按模型有不同的 QPS 限制',
      '免费版 QPS 较低',
      '可申请提升配额',
    ],
    usageMethodInfo: [
      '兼容 OpenAI Chat Completions API',
      '支持多轮对话和流式输出',
      '支持函数调用',
    ],
    validityInfo: [
      '免费额度有使用期限',
      '付费按调用量计费',
      '可在腾讯云控制台查看',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'hunyuan-lite',
    apiBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在腾讯云控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.hunyuan.cloud.tencent.com/v1/models',
  },
  {
    key: 'xfyun',
    name: '讯飞星火',
    region: 'domestic',
    websiteUrl: 'https://xinghuo.xfyun.cn',
    consoleUrl: 'https://console.xfyun.cn/services/bm35',
    apiDocUrl: 'https://www.xfyun.cn/doc/spark',
    freeTierInfo: [
      '新用户注册赠送免费 token 额度',
      'Spark-Lite 模型提供免费调用',
      '每日有免费调用次数',
    ],
    rateLimitInfo: [
      '不同版本有不同的并发限制',
      '免费版 QPS 有限',
      '超出限制需等待或升级',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持 WebSocket 和 HTTP 调用',
      '支持多模态和插件',
    ],
    validityInfo: [
      '免费额度有有效期限制',
      '资源包过期失效',
      '可在控制台查看剩余量',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'spark-lite',
    apiBaseUrl: 'https://spark-api-open.xf-yun.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在讯飞开放平台控制台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://spark-api-open.xf-yun.com/v1/models',
  },
  {
    key: 'doubao',
    name: '火山引擎方舟/豆包',
    region: 'domestic',
    websiteUrl: 'https://www.volcengine.com/product/ark',
    consoleUrl: 'https://console.volcengine.com/ark',
    apiDocUrl: 'https://www.volcengine.com/docs/82379',
    freeTierInfo: [
      '新用户注册赠送大量免费额度',
      'Doubao 系列模型提供免费调用',
      '有百万级 token 免费体验',
    ],
    rateLimitInfo: [
      '不同模型有不同的 TPM/RPM',
      '免费版有限速',
      '可通过付费提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI Chat Completions API',
      '支持流式输出和函数调用',
      '支持多模态和知识库',
    ],
    validityInfo: [
      '免费额度有使用期限',
      '按量付费无有效期',
      '可在火山引擎控制台查看',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'doubao-seed-1-6-flash-250828',
    apiBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在火山引擎控制台查看用量',
    modelsApiType: 'volcengine-ark',
    modelsApiUrl: 'https://ark.cn-beijing.volcengineapi.com/?Action=ListFoundationModels&Version=2024-01-01',
    supportsAkSk: true,
    builtinModelsUpdatedAt: '2026-09-08',
    builtinModels: [
      { id: 'doubao-seed-2-1-pro-260628', name: 'Doubao Seed 2.1 Pro', contextLength: 128000, pricingNote: '按量计费/见官方定价' },
      { id: 'doubao-seed-1-8-251228', name: 'Doubao Seed 1.8', contextLength: 128000, pricingNote: '按量计费/见官方定价' },
      { id: 'doubao-seed-1-6-flash-250828', name: 'Doubao Seed 1.6 Flash（即将下线）', contextLength: 128000, isDeprecated: true, pricingNote: '按量计费/见官方定价' },
      { id: 'doubao-seed-1-6-flash-250615', name: 'Doubao Seed 1.6 Flash（即将下线）', contextLength: 128000, isDeprecated: true, pricingNote: '按量计费/见官方定价' },
      { id: 'doubao-seed-1-6-250615', name: 'Doubao Seed 1.6（即将下线）', contextLength: 128000, isDeprecated: true, pricingNote: '按量计费/见官方定价' },
      { id: 'deepseek-v4-pro-260425', name: 'DeepSeek V4 Pro', contextLength: 128000, pricingNote: '按量计费/见官方定价' },
      { id: 'deepseek-v4-flash-260425', name: 'DeepSeek V4 Flash', contextLength: 128000, pricingNote: '按量计费/见官方定价' },
      { id: 'deepseek-v3-2-251201', name: 'DeepSeek V3.2', contextLength: 128000, pricingNote: '按量计费/见官方定价' },
      { id: 'glm-4-7-251222', name: 'GLM-4.7', contextLength: 128000, pricingNote: '按量计费/见官方定价' },
    ],
  },
  {
    key: 'deepseek',
    name: 'DeepSeek',
    region: 'domestic',
    websiteUrl: 'https://www.deepseek.com',
    consoleUrl: 'https://platform.deepseek.com/api_keys',
    apiDocUrl: 'https://platform.deepseek.com/docs',
    freeTierInfo: [
      '新用户注册赠送 500 万 tokens',
      'DeepSeek-Chat 模型低价可用',
      '有免费试用额度',
    ],
    rateLimitInfo: [
      '默认有 RPM/TPM 限制',
      '可申请提升速率限制',
      '超出返回 429',
    ],
    usageMethodInfo: [
      '完全兼容 OpenAI API',
      '支持流式输出和函数调用',
      '支持推理模型',
    ],
    validityInfo: [
      '新用户赠送额度有有效期',
      '充值金额长期有效',
      '可在平台查看账单明细',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'deepseek-chat',
    apiBaseUrl: 'https://api.deepseek.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '可在平台页面查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.deepseek.com/v1/models',
  },
  {
    key: 'minimax',
    name: 'MiniMax',
    region: 'domestic',
    websiteUrl: 'https://www.minimaxi.com',
    consoleUrl: 'https://api.minimax.chat/user-center/basic-information/interface-key',
    apiDocUrl: 'https://api.minimax.chat/document',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'ABAB6.5s 等模型可免费体验',
      '有一定量的免费调用次数',
    ],
    rateLimitInfo: [
      '不同模型有不同 QPS 限制',
      '免费版 QPS 较低',
      '可申请提升配额',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持语音合成和语音识别',
      '支持多模态能力',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额长期有效',
      '可在控制台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'abab6.5s-chat',
    apiBaseUrl: 'https://api.minimax.chat/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 MiniMax 控制台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.minimax.chat/v1/models',
  },
  {
    key: 'moonshot',
    name: '月之暗面Kimi',
    region: 'domestic',
    websiteUrl: 'https://www.moonshot.cn',
    consoleUrl: 'https://platform.moonshot.cn/console/api-keys',
    apiDocUrl: 'https://platform.moonshot.cn/docs',
    freeTierInfo: [
      '新用户注册赠送 15 元额度',
      'Moonshot-v1 系列均可使用',
      '支持长文本上下文',
    ],
    rateLimitInfo: [
      '免费版有 RPM/TPM 限制',
      '可通过充值提升',
      '超出限制返回 429',
    ],
    usageMethodInfo: [
      '兼容 OpenAI Chat Completions',
      '支持 128K 长上下文',
      '支持文件理解',
    ],
    validityInfo: [
      '赠送额度有使用期限',
      '充值余额无有效期',
      '可在平台查看消费明细',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'moonshot-v1-8k',
    apiBaseUrl: 'https://api.moonshot.cn/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '可在平台控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.moonshot.cn/v1/models',
  },
  {
    key: 'stepfun',
    name: '阶跃星辰',
    region: 'domestic',
    websiteUrl: 'https://www.stepfun.com',
    consoleUrl: 'https://platform.stepfun.com/account/apiKey',
    apiDocUrl: 'https://platform.stepfun.com/docs',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Step-1-Flash 模型免费',
      '有一定量的免费 token',
    ],
    rateLimitInfo: [
      '不同模型有不同速率限制',
      '免费版有 QPS 限制',
      '可升级提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持多模态理解',
      '支持流式输出',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额长期有效',
      '可在控制台查看账单',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'step-1-flash',
    apiBaseUrl: 'https://api.stepfun.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在阶跃星辰平台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.stepfun.com/v1/models',
  },
  {
    key: 'siliconflow',
    name: '硅基流动',
    region: 'domestic',
    websiteUrl: 'https://www.siliconflow.cn',
    consoleUrl: 'https://cloud.siliconflow.cn/account/ak',
    apiDocUrl: 'https://docs.siliconflow.cn',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      '多款开源模型免费调用',
      '每日有免费调用次数',
    ],
    rateLimitInfo: [
      '免费模型每日有调用次数限制',
      '付费模型按 token 计费',
      '有 RPM/TPM 限制',
    ],
    usageMethodInfo: [
      '完全兼容 OpenAI API',
      '支持大量开源模型',
      '支持文生图和 Embedding',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额可长期使用',
      '可在控制台查看明细',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'Qwen/Qwen2.5-7B-Instruct',
    apiBaseUrl: 'https://api.siliconflow.cn/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '可在硅基流动控制台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.siliconflow.cn/v1/models',
  },
  {
    key: 'openbmb',
    name: 'OpenBMB',
    region: 'domestic',
    websiteUrl: 'https://www.openbmb.cn',
    consoleUrl: 'https://modelbest.cn/',
    apiDocUrl: 'https://modelbest.cn/docs',
    freeTierInfo: [
      '提供免费模型调用额度',
      'MiniCPM 系列模型可免费使用',
      '适合轻量级任务',
    ],
    rateLimitInfo: [
      '免费版有速率限制',
      '不同模型 QPS 不同',
      '可联系提升配额',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持多模态小模型',
      '支持本地部署和云端调用',
    ],
    validityInfo: [
      '免费额度长期有效',
      '可在平台查看用量',
      '企业版定制化计费',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'MiniCPM5-2B',
    apiBaseUrl: 'https://api.modelbest.cn/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在平台控制台查看用量',
    modelsApiType: 'none',
  },
  {
    key: 'lingyi',
    name: '零一万物',
    region: 'domestic',
    websiteUrl: 'https://www.lingyiwanwu.com',
    consoleUrl: 'https://platform.lingyiwanwu.com/apikeys',
    apiDocUrl: 'https://platform.lingyiwanwu.com/docs',
    freeTierInfo: [
      'API 服务已关停',
      '原有的免费额度已不可用',
      '建议迁移至其他平台',
    ],
    rateLimitInfo: [
      '服务已关停',
      '不再接受新的调用请求',
      '原有 Key 已失效',
    ],
    usageMethodInfo: [
      'API 服务已停止',
      '建议使用其他平台替代',
      '官网可了解最新动态',
    ],
    validityInfo: [
      'API 服务已于 2024 年底关停',
      '剩余额度不再有效',
      '关注官方公告获取最新消息',
    ],
    requiresRealName: true,
    status: '已关停',
    statusNote: '零一万物 API 服务已关停，无法调用',
    testModel: 'yi-lightning',
    apiBaseUrl: 'https://api.lingyiwanwu.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '服务已关停',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.lingyiwanwu.com/v1/models',
  },
  {
    key: 'baichuan',
    name: '百川智能',
    region: 'domestic',
    websiteUrl: 'https://www.baichuan-ai.com',
    consoleUrl: 'https://platform.baichuan-ai.com/console/apikey',
    apiDocUrl: 'https://platform.baichuan-ai.com/docs',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Baichuan3-Turbo 可体验',
      '有一定量的免费调用',
    ],
    rateLimitInfo: [
      '免费版有 QPS 限制',
      '不同模型速率不同',
      '可申请提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持长文本理解',
      '支持知识库和搜索增强',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额长期有效',
      '可在控制台查看用量',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'Baichuan3-Turbo',
    apiBaseUrl: 'https://api.baichuan-ai.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在百川智能平台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.baichuan-ai.com/v1/models',
  },
  {
    key: 'sensenova',
    name: '商汤日日新',
    region: 'domestic',
    websiteUrl: 'https://www.sensetime.com/cn/technology',
    consoleUrl: 'https://console.sensecore.cn',
    apiDocUrl: 'https://platform.sensenova.cn/doc',
    freeTierInfo: [
      '公测期间免费使用',
      '多款模型免费调用体验',
      '新用户注册即送额度',
    ],
    rateLimitInfo: [
      '公测版有速率限制',
      'QPS 有限制',
      '正式版可提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持多模态能力',
      '支持数字人等特色功能',
    ],
    validityInfo: [
      '公测期间免费',
      '正式商用后按用量计费',
      '可在控制台查看',
    ],
    requiresRealName: true,
    status: '公测免费中',
    statusNote: '商汤日日新处于公测阶段，可免费体验',
    testModel: 'sensenova-6.7-flash-lite',
    apiBaseUrl: 'https://api.sensenova.cn/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '公测阶段需在控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.sensenova.cn/v1/models',
  },
  {
    key: 'youdao',
    name: '网易有道子曰',
    region: 'domestic',
    websiteUrl: 'https://ai.youdao.com',
    consoleUrl: 'https://ai.youdao.com/console',
    apiDocUrl: 'https://ai.youdao.com/DOCSIRMA/html',
    freeTierInfo: [
      '新用户注册赠送免费体验额度',
      '子曰大模型可免费试用',
      '翻译等经典接口有免费额度',
    ],
    rateLimitInfo: [
      '不同接口 QPS 限制不同',
      '免费版有调用次数限制',
      '可付费提升限额',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持翻译、问答等多种能力',
      '教育场景优化',
    ],
    validityInfo: [
      '免费额度有有效期',
      '按量付费无期限',
      '可在控制台查看账单',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'qs-chat',
    apiBaseUrl: 'https://openapi.youdao.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在有道智云控制台查看',
    modelsApiType: 'none',
  },
  {
    key: 'yanxi',
    name: '京东言犀',
    region: 'domestic',
    websiteUrl: 'https://yanxi.jd.com',
    consoleUrl: 'https://console.jdcloud.com',
    apiDocUrl: 'https://docs.jdcloud.com/cn',
    freeTierInfo: [
      '新用户可领取免费额度',
      'JD-LLM 模型可体验',
      '电商场景优化',
    ],
    rateLimitInfo: [
      '有 QPS 和并发限制',
      '免费版速率较低',
      '企业版可定制',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持电商知识库',
      '支持客服场景',
    ],
    validityInfo: [
      '免费额度有使用期限',
      '按量付费实时结算',
      '可在京东云控制台查看',
    ],
    requiresRealName: true,
    status: '正常',
    testModel: 'jd-llm',
    apiBaseUrl: 'https://aiapi.jdcloud.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在京东云控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://aiapi.jdcloud.com/v1/models',
  },
  {
    key: 'mianbi',
    name: '面壁智能',
    region: 'domestic',
    websiteUrl: 'https://www.modelbest.cn',
    consoleUrl: 'https://modelbest.cn/',
    apiDocUrl: 'https://modelbest.cn/docs',
    freeTierInfo: [
      'MiniCPM 系列模型免费',
      '提供轻量级模型调用',
      '适合端侧和边缘部署',
    ],
    rateLimitInfo: [
      '免费版有速率限制',
      '不同模型 QPS 不同',
      '企业版可提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持多模态小模型',
      '支持本地部署方案',
    ],
    validityInfo: [
      '免费模型长期可用',
      '企业版定制化计费',
      '可在平台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'minicpm5-2b',
    apiBaseUrl: 'https://api.modelbest.cn/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在面壁智能平台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.modelbest.cn/v1/models',
  },

  // ========== 国外 20 家 ==========
  {
    key: 'gemini',
    name: 'Google Gemini',
    region: 'overseas',
    websiteUrl: 'https://ai.google.dev',
    consoleUrl: 'https://aistudio.google.com/app/apikey',
    apiDocUrl: 'https://ai.google.dev/docs',
    freeTierInfo: [
      'Gemini 2.5 Flash 免费版每分钟 15 次请求',
      '每天 1500 次免费请求',
      '适合轻量级应用和开发测试',
    ],
    rateLimitInfo: [
      '免费版 RPM 15，RPD 1500',
      '付费版可提升至更高 TPM/RPM',
      '不同模型限制不同',
    ],
    usageMethodInfo: [
      '使用 API Key 作为 query 参数',
      '支持多模态、函数调用',
      '支持流式输出',
    ],
    validityInfo: [
      '免费额度无过期时间',
      '按量付费无有效期',
      '可在 Google Cloud 控制台查看',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'gemini-2.5-flash',
    apiBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    authType: 'query',
    hasUsageApi: false,
    usageApiNote: '需在 Google AI Studio 查看用量',
    modelsApiType: 'gemini',
    modelsApiUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
  },
  {
    key: 'groq',
    name: 'Groq',
    region: 'overseas',
    websiteUrl: 'https://groq.com',
    consoleUrl: 'https://console.groq.com/keys',
    apiDocUrl: 'https://console.groq.com/docs',
    freeTierInfo: [
      '永久免费层（速率有限制）',
      '多款热门模型免费调用',
      '速度极快，推理延迟低',
    ],
    rateLimitInfo: [
      '免费版有 RPM 和 TPM 限制',
      '响应头返回剩余配额信息',
      '超出限制返回 429',
    ],
    usageMethodInfo: [
      '完全兼容 OpenAI API',
      '支持流式输出',
      '支持函数调用',
    ],
    validityInfo: [
      '免费层永久可用',
      '付费版按需计费',
      '可在控制台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'llama-3.3-70b-versatile',
    apiBaseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    hasUsageApi: true,
    usageApiNote: '响应头中包含速率限制和用量信息',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.groq.com/openai/v1/models',
  },
  {
    key: 'openrouter',
    name: 'OpenRouter',
    region: 'overseas',
    websiteUrl: 'https://openrouter.ai',
    consoleUrl: 'https://openrouter.ai/keys',
    apiDocUrl: 'https://openrouter.ai/docs',
    freeTierInfo: [
      '提供多种免费模型可供选择',
      '新用户可能获得免费额度',
      '支持按模型付费或免费模型',
    ],
    rateLimitInfo: [
      '不同模型速率限制不同',
      '免费模型有每日限制',
      '可通过付费提升',
    ],
    usageMethodInfo: [
      '完全兼容 OpenAI API',
      '聚合上百种模型',
      '支持流式输出',
    ],
    validityInfo: [
      '充值余额长期有效',
      '免费模型持续可用',
      '可查询余额和用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'meta-llama/llama-3.1-8b-instruct:free',
    apiBaseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    hasUsageApi: true,
    usageApiNote: '提供 /credits 接口查询余额',
    modelsApiType: 'openrouter',
    modelsApiUrl: 'https://openrouter.ai/api/v1/models',
  },
  {
    key: 'mistral',
    name: 'Mistral AI',
    region: 'overseas',
    websiteUrl: 'https://mistral.ai',
    consoleUrl: 'https://console.mistral.ai/api-keys',
    apiDocUrl: 'https://docs.mistral.ai',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Mistral Small 等模型可用',
      '支持免费试用',
    ],
    rateLimitInfo: [
      '有 RPM/TPM 限制',
      '可申请提升配额',
      '超出返回 429',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持函数调用',
      '支持 Embedding',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额可用',
      '可在控制台查看',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'mistral-small-latest',
    apiBaseUrl: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Mistral 控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.mistral.ai/v1/models',
  },
  {
    key: 'cohere',
    name: 'Cohere',
    region: 'overseas',
    websiteUrl: 'https://cohere.com',
    consoleUrl: 'https://dashboard.cohere.com/api-keys',
    apiDocUrl: 'https://docs.cohere.com',
    freeTierInfo: [
      '免费试用层可用',
      'Command 系列模型可体验',
      '适合 NLP 和 RAG 场景',
    ],
    rateLimitInfo: [
      '免费版有速率限制',
      '每分钟请求数有限',
      '付费版可提升',
    ],
    usageMethodInfo: [
      '提供 Chat、Generate、Embed 等接口',
      '支持 RAG 和知识库',
      '支持流式输出',
    ],
    validityInfo: [
      '免费试用有额度限制',
      '生产环境需付费',
      '可在 Dashboard 查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'command-r',
    apiBaseUrl: 'https://api.cohere.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Cohere Dashboard 查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.cohere.com/v1/models',
  },
  {
    key: 'cloudflare',
    name: 'Cloudflare Workers AI',
    region: 'overseas',
    websiteUrl: 'https://workers.cloudflare.com',
    consoleUrl: 'https://dash.cloudflare.com',
    apiDocUrl: 'https://developers.cloudflare.com/workers-ai',
    freeTierInfo: [
      '免费方案每日 10000 次神经元',
      '支持 Workers 中调用',
      '全球边缘节点部署',
    ],
    rateLimitInfo: [
      '免费方案每日有限额',
      '付费版按神经元计费',
      '有并发限制',
    ],
    usageMethodInfo: [
      '需 Account ID + API Token',
      '可在 Worker 中直接调用',
      '支持 REST API 调用',
    ],
    validityInfo: [
      '免费额度每日重置',
      '付费按用量计费',
      '可在 Cloudflare 控制台查看',
    ],
    requiresRealName: false,
    status: '正常',
    statusNote: '需要 Account ID 和 API Token 组合使用',
    testModel: '@cf/meta/llama-3-8b-instruct',
    apiBaseUrl: 'https://api.cloudflare.com/client/v4/accounts',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Cloudflare 控制台查看用量',
    modelsApiType: 'none',
  },
  {
    key: 'cerebras',
    name: 'Cerebras',
    region: 'overseas',
    websiteUrl: 'https://www.cerebras.net',
    consoleUrl: 'https://cloud.cerebras.ai',
    apiDocUrl: 'https://inference-docs.cerebras.ai',
    freeTierInfo: [
      '提供免费试用额度',
      'Llama 系列模型可体验',
      '推理速度极快',
    ],
    rateLimitInfo: [
      '免费版速率有限制',
      '有并发数限制',
      '可升级提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '使用专用推理芯片',
      '支持流式输出',
    ],
    validityInfo: [
      '免费试用有额度限制',
      '付费按需计费',
      '可在平台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'llama3.1-8b',
    apiBaseUrl: 'https://api.cerebras.ai/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Cerebras 控制台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.cerebras.ai/v1/models',
  },
  {
    key: 'github',
    name: 'GitHub Models',
    region: 'overseas',
    websiteUrl: 'https://github.com/marketplace/models',
    consoleUrl: 'https://github.com/settings/tokens',
    apiDocUrl: 'https://docs.github.com/en/github-models',
    freeTierInfo: [
      '提供免费模型调用额度',
      'GPT-4o-mini 等模型免费',
      'GitHub 账户即可使用',
    ],
    rateLimitInfo: [
      '免费版有每日调用限制',
      '不同模型限额不同',
      '超出需要付费',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '使用 GitHub Token 认证',
      '支持多种热门模型',
    ],
    validityInfo: [
      '免费额度每日重置',
      '付费按需计费',
      '可在 GitHub 查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'gpt-4o-mini',
    apiBaseUrl: 'https://models.inference.ai.azure.com',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 GitHub 页面查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://models.inference.ai.azure.com/models',
  },
  {
    key: 'openai',
    name: 'OpenAI',
    region: 'overseas',
    websiteUrl: 'https://openai.com',
    consoleUrl: 'https://platform.openai.com/api-keys',
    apiDocUrl: 'https://platform.openai.com/docs',
    freeTierInfo: [
      '无永久免费层',
      '新用户可能获得 5 美元试用额度',
      '需绑定信用卡使用',
    ],
    rateLimitInfo: [
      '按组织和项目有 RPM/TPM 限制',
      '不同模型限制不同',
      '可申请提升配额',
    ],
    usageMethodInfo: [
      '业界标准 API 格式',
      '支持 Chat、Embedding、Fine-tuning',
      '支持函数调用和多模态',
    ],
    validityInfo: [
      '试用额度有使用期限',
      '付费按量计费',
      '可在 Usage 页面查看',
    ],
    requiresRealName: false,
    status: '无免费层',
    statusNote: 'OpenAI 无免费层，需要付费使用',
    testModel: 'gpt-4o-mini',
    apiBaseUrl: 'https://api.openai.com/v1',
    authType: 'bearer',
    hasUsageApi: true,
    usageApiNote: '提供 Usage API 查询用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.openai.com/v1/models',
  },
  {
    key: 'together',
    name: 'Together AI',
    region: 'overseas',
    websiteUrl: 'https://www.together.ai',
    consoleUrl: 'https://api.together.xyz/settings/api-keys',
    apiDocUrl: 'https://docs.together.ai',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      '支持大量开源模型',
      '适合推理和微调',
    ],
    rateLimitInfo: [
      '有速率和并发限制',
      '不同模型 QPS 不同',
      '可申请提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持模型微调',
      '支持 Embedding',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额可用',
      '可在控制台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'meta-llama/Llama-3-8b-chat-hf',
    apiBaseUrl: 'https://api.together.xyz/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Together 控制台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.together.xyz/v1/models',
  },
  {
    key: 'fireworks',
    name: 'Fireworks AI',
    region: 'overseas',
    websiteUrl: 'https://fireworks.ai',
    consoleUrl: 'https://fireworks.ai/account/api-keys',
    apiDocUrl: 'https://fireworks.ai/docs',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      '支持 Llama、Mistral 等模型',
      '推理速度快',
    ],
    rateLimitInfo: [
      '有 RPM/TPM 限制',
      '免费版速率有限',
      '付费可提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持函数调用',
      '支持视觉模型',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额长期可用',
      '可在控制台查看账单',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
    apiBaseUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Fireworks 控制台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.fireworks.ai/inference/v1/models',
  },
  {
    key: 'replicate',
    name: 'Replicate',
    region: 'overseas',
    websiteUrl: 'https://replicate.com',
    consoleUrl: 'https://replicate.com/account/api-tokens',
    apiDocUrl: 'https://replicate.com/docs',
    freeTierInfo: [
      '无免费层，按量付费',
      '新用户可能获得少量试用额度',
      '需绑定信用卡',
    ],
    rateLimitInfo: [
      '有并发数限制',
      '可创建专用实例提升',
      '按秒计费',
    ],
    usageMethodInfo: [
      '提供 REST API 调用',
      '支持数千种开源模型',
      '支持训练和微调',
    ],
    validityInfo: [
      '试用额度有有效期',
      '按量付费实时扣费',
      '可在 Dashboard 查看',
    ],
    requiresRealName: false,
    status: '无免费层',
    statusNote: 'Replicate 无免费层，按调用量计费',
    testModel: 'meta/llama-3-8b-instruct',
    apiBaseUrl: 'https://api.replicate.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Replicate 控制台查看用量',
    modelsApiType: 'none',
  },
  {
    key: 'huggingface',
    name: 'Hugging Face',
    region: 'overseas',
    websiteUrl: 'https://huggingface.co',
    consoleUrl: 'https://huggingface.co/settings/tokens',
    apiDocUrl: 'https://huggingface.co/docs/api-inference',
    freeTierInfo: [
      'Inference API 免费使用',
      '部分模型有速率限制',
      '适合测试和轻量使用',
    ],
    rateLimitInfo: [
      '免费版有速率限制',
      '热门模型可能排队',
      'Pro 版可提升',
    ],
    usageMethodInfo: [
      '使用 Inference API 调用',
      '支持所有 Transformers 模型',
      '支持文本、图像、音频',
    ],
    validityInfo: [
      '免费层持续可用',
      'Pro 订阅按月计费',
      '可在账户页面查看',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'meta-llama/Meta-Llama-3-8B-Instruct',
    apiBaseUrl: 'https://api-inference.huggingface.co/models',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Hugging Face 页面查看用量',
    modelsApiType: 'none',
  },
  {
    key: 'anthropic',
    name: 'Anthropic',
    region: 'overseas',
    websiteUrl: 'https://www.anthropic.com',
    consoleUrl: 'https://console.anthropic.com/settings/keys',
    apiDocUrl: 'https://docs.anthropic.com',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Claude Haiku 等模型可用',
      '支持长上下文',
    ],
    rateLimitInfo: [
      '有 RPM 和 TPM 限制',
      '不同层级限制不同',
      '超出返回 429',
    ],
    usageMethodInfo: [
      '使用 x-api-key header 认证',
      'Messages API 调用',
      '支持流式输出和工具调用',
    ],
    validityInfo: [
      '免费额度有使用期限',
      '按量付费无限制',
      '可在控制台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'claude-3-haiku-20240307',
    apiBaseUrl: 'https://api.anthropic.com/v1',
    authType: 'header-custom',
    hasUsageApi: false,
    usageApiNote: '需在 Anthropic 控制台查看用量',
    modelsApiType: 'none',
  },
  {
    key: 'perplexity',
    name: 'Perplexity API',
    region: 'overseas',
    websiteUrl: 'https://www.perplexity.ai',
    consoleUrl: 'https://www.perplexity.ai/settings/api',
    apiDocUrl: 'https://docs.perplexity.ai',
    freeTierInfo: [
      '新用户提供免费试用额度',
      'PPLX 系列模型可体验',
      '搜索增强能力',
    ],
    rateLimitInfo: [
      '有请求数限制',
      '免费版速率有限',
      '付费可提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI Chat API',
      '支持联网搜索',
      '支持流式输出',
    ],
    validityInfo: [
      '试用额度有有效期',
      '按量付费计费',
      '可在账户设置查看',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'pplx-7b-chat',
    apiBaseUrl: 'https://api.perplexity.ai',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Perplexity 账户设置查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.perplexity.ai/models',
  },
  {
    key: 'ai21',
    name: 'AI21 Labs',
    region: 'overseas',
    websiteUrl: 'https://www.ai21.com',
    consoleUrl: 'https://studio.ai21.com/account/api-key',
    apiDocUrl: 'https://docs.ai21.com',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      'Jamba 系列模型可体验',
      '适合文本生成任务',
    ],
    rateLimitInfo: [
      '有 RPM 限制',
      '免费版速率有限',
      '可申请提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持文本补全和聊天',
      '支持 RAG 功能',
    ],
    validityInfo: [
      '免费额度有有效期',
      '按量付费可用',
      '可在 Studio 查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'jamba-1.5-mini',
    apiBaseUrl: 'https://api.ai21.com/studio/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 AI21 Studio 查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.ai21.com/studio/v1/models',
  },
  {
    key: 'writer',
    name: 'Writer',
    region: 'overseas',
    websiteUrl: 'https://writer.com',
    consoleUrl: 'https://writer.com/studio',
    apiDocUrl: 'https://dev.writer.com',
    freeTierInfo: [
      '提供免费试用额度',
      'Palmyra 系列模型可体验',
      '企业级文本生成',
    ],
    rateLimitInfo: [
      '有 API 调用速率限制',
      '不同套餐限制不同',
      '企业版可定制',
    ],
    usageMethodInfo: [
      '提供 REST API',
      '支持内容生成和改写',
      '支持企业知识库',
    ],
    validityInfo: [
      '试用额度有期限',
      '企业套餐按月计费',
      '可在控制台查看',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'palmyra-x-003',
    apiBaseUrl: 'https://api.writer.com/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Writer 控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.writer.com/v1/models',
  },
  {
    key: 'deepinfra',
    name: 'DeepInfra',
    region: 'overseas',
    websiteUrl: 'https://deepinfra.com',
    consoleUrl: 'https://deepinfra.com/dashboard',
    apiDocUrl: 'https://deepinfra.com/docs',
    freeTierInfo: [
      '无免费层，按量付费',
      '新用户可能有少量试用额度',
      '支持大量开源模型',
    ],
    rateLimitInfo: [
      '有并发数限制',
      '不同模型速率不同',
      '可提升配额',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持文本、图像、语音',
      '支持部署私有模型',
    ],
    validityInfo: [
      '试用额度有有效期',
      '按量付费按秒计费',
      '可在 Dashboard 查看',
    ],
    requiresRealName: false,
    status: '无免费层',
    statusNote: 'DeepInfra 无免费层，按用量计费',
    testModel: 'meta-llama/Meta-Llama-3-8B-Instruct',
    apiBaseUrl: 'https://api.deepinfra.com/v1/openai',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 DeepInfra 控制台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.deepinfra.com/v1/openai/models',
  },
  {
    key: 'novita',
    name: 'Novita AI',
    region: 'overseas',
    websiteUrl: 'https://novita.ai',
    consoleUrl: 'https://platform.novita.ai',
    apiDocUrl: 'https://docs.novita.ai',
    freeTierInfo: [
      '新用户注册赠送免费额度',
      '支持 Llama、Mistral 等模型',
      '文生图模型丰富',
    ],
    rateLimitInfo: [
      '有 RPM 限制',
      '免费版速率有限',
      '付费可提升',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持大模型和图像生成',
      '支持 LoRA 模型',
    ],
    validityInfo: [
      '免费额度有有效期',
      '充值余额长期可用',
      '可在平台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'meta-llama/Llama-3.1-8B-Instruct',
    apiBaseUrl: 'https://api.novita.ai/v3/openai',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 Novita AI 平台查看',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.novita.ai/v3/openai/models',
  },
  {
    key: 'sambanova',
    name: 'SambaNova',
    region: 'overseas',
    websiteUrl: 'https://sambanova.ai',
    consoleUrl: 'https://cloud.sambanova.ai',
    apiDocUrl: 'https://docs.sambanova.ai/cloud',
    freeTierInfo: [
      '提供免费试用额度',
      'Llama 系列模型可体验',
      '专用硬件加速',
    ],
    rateLimitInfo: [
      '有速率限制',
      '免费版有限额',
      '企业版可定制',
    ],
    usageMethodInfo: [
      '兼容 OpenAI API 格式',
      '支持流式输出',
      '支持函数调用',
    ],
    validityInfo: [
      '免费额度有有效期',
      '企业版按合同计费',
      '可在平台查看用量',
    ],
    requiresRealName: false,
    status: '正常',
    testModel: 'Meta-Llama-3.1-8B-Instruct',
    apiBaseUrl: 'https://api.sambanova.ai/v1',
    authType: 'bearer',
    hasUsageApi: false,
    usageApiNote: '需在 SambaNova 平台查看用量',
    modelsApiType: 'openai-compatible',
    modelsApiUrl: 'https://api.sambanova.ai/v1/models',
  },
];

export function getPlatformMap(): Map<string, PlatformInfo> {
  const map = new Map<string, PlatformInfo>();
  for (const p of PLATFORMS) {
    map.set(p.key, p);
  }
  return map;
}
